### ISSUE TITLE
ImageLab React - milestones for GSoC 2023

### ISSUE THREAD

**Issue by abdullahranginwala** [scorelab/imagelab#149]
Following are the milestones for GSoC 2023

## Milestone 1 (UI/UX Revamp)
- [x] Proof of concept for electron app built on top of react
- [x] Integrate react-blockly framework
- [x] Initialise new project
- [x] Rewrite UI components in React based on updated design
- [x] Migrate boilerplate code from original project
- [x] Connect the backend with the new UI

## Milestone 2 (Add testing framework)
- [x] Finalize testing framework
- [x] Write unit and end to end tests for the React & Electron App

## Milestone 3 (Implement video processing operators)
- [ ] Implement the meanShift operator
- [ ] Implement the camShift operator
- [ ] Implement the Dense Optical flow operator
- [ ] Implement the background subtraction operator

## Milestone 4 (Implement neural network operators)
- [x] Implement the image-classification operator
- [x] Implement the Object Detection operator
- [x] Implement the Semantic Segmentation operator
- [x] Implement the Style Transfer operator
- [x] Implement the Pose Estimation operator
- [ ] Configure import model block

## Milestone 5 (Documentation)
- [x] Update the documentation based on the frameworks used
- [x] Update the Readme and contributing docs to comprehensively cover the entire electron project
