### ISSUE TITLE
ImageLab - extend the functionality milestones for GSoC 2021 

### ISSUE THREAD

**Issue by SahanDisa** [scorelab/imagelab#65]
Following higher-level milestones and tasks needs to be discussed and finalized in the GSoC 2021 under ImageLab - extend the functionality.

### Milestone 1 - Architecture Improvements
- [x] Finalize the implementation of architecture changes to the code
### Milestone 2 - Implementation of the OpenCV operators(Phase 01) 
- [x] Implement Extended geometric transformation operators
- [x] Implement Extended filtering operators
- [x] Implement Drawing operators
- [x] Implement Morphological operators
- [x] Implement Sobel Derivation
- [x] Implement Transformation operators
### Milestone 3 - Implementation of the OpenCV operators(Phase 02) 
- [x] Implement Histogram operators
- [x] Implement Contour operators
- [x] Implement Miscellaneous operators 
- [x] Implement Image Segmentation with Distance Transform and Watershed Algorithm
- [x] Export OpenCV Operation Stream as an illustration
### Milestone 4 - Implementation of visualization pane and application section
- [x] Implement the visualization pane section using histograms
- [x] Implement the application section with predefined operator streams
### Milestone 5 - Testing
- [x] Writing tests to evaluate developed features
### Milestone 6 - Documentation
 - [x] Updating the project documentation for newly created functionality
 - [x] Updating project README with relevant information

**Comment by ghost** [comment]
i wanna work on this issue
