### ISSUE TITLE
Improve Image Lab UI/UX - GSoC 2021

### ISSUE THREAD

**Issue by polahano** [scorelab/imagelab#66]
# GSoC 2021 Milestones

## Phase 1
- [x] Designing a logo for ImageLab project
- [x] Designing a splash screen (loading screen)
- [x] Making a quick guide on the first use
- [x] Improving the project User Interface and implementing it
- [x] Adding night mode
- [x] Designing new block shapes and replacing all blocks with the new design
- [x] Adding zooming in the playground and also in preview pane.
- [x] Add save or don’t save pipeline option when closing the app.

## Phase 2
- [ ] Enhance the view of the project documentation.
- [x] Improve new way for unmergeable blocks.
- [ ] Adding help section
- [x] Adding Info (About us) section
- [x] Providing availability for all image sizes
- [ ] Adding history pane
- [x] Drag and drop in basket to remove a specific filter
- [x] Add (new pipeline) button
- [ ] Package the application into an installable exe file in windows
- [x] Run with keyboard shortcut.

Here are some a picture shows my imagination about the new UI :

![ImageLab UI](https://user-images.githubusercontent.com/43797542/118885571-3f664800-b8f8-11eb-8b32-287894b12435.jpg)

For detailed information you can check [my proposal](https://github.com/polahano/GSoC-2021/blob/main/GSoC-Improving%20Image%20Lab%20UI-UX%20Proposal.pdf)

*Your feedbacks are much welcomed !*

**Comment by ghost** [comment]
i wanna work on this issue
